# Generated by Django 4.2.3 on 2023-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz_Game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.CharField(max_length=500)),
                ("ans1", models.CharField(max_length=500)),
                ("ans2", models.CharField(max_length=500)),
                ("ans3", models.CharField(max_length=500)),
                ("ans4", models.CharField(max_length=500)),
            ],
        ),
    ]
