# Generated by Django 4.2.3 on 2023-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Game', '0004_rename_ans_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
